image: wener/node:docker
stages:
  - build

Build Image:
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - mkdir /etc/apk/cache
    # canvas
    # https://github.com/Automattic/node-canvas/issues/1065#issuecomment-445548120
    - apk add cairo-dev pango-dev jpeg-dev pixman-dev
    - apk add rsync jq
#    - ./build/build-apis.sh
    - echo Building image "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"

cache:
  untracked: true
  key: "$CI_COMMIT_REF_NAME"
  paths:
    # - node_modules/
    - .yarn/
    - packages/server/.next/cache/
    - /etc/apk/cache
