changesetIgnorePatterns:
  - "**/*.test.{js,ts,tsx}"

enableTelemetry: 0

immutablePatterns:
  - .pnp.*

initScope: wener

npmPublishAccess: public

npmRegistryServer: "https://registry.npm.taobao.org"

npmPublishRegistry: https://registry.npmjs.org/

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-stage.cjs
    spec: "@yarnpkg/plugin-stage"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

pnpMode: loose

preferInteractive: true

yarnPath: .yarn/releases/yarn-2.2.0.cjs
