// generated:begin@types
export const iconsResolverTypes: string[] = [
  'BarcodePrintOutlined',
  'BarcodeReadOutlined',
  'BarcodeScanOutlined',
  'BittorrentFilled',
  'BtFileFilled',
  'CaCertificateOutlined',
  'CertificateVerifiedBadgeOutlined',
  'CertificateVerifiedFilled',
  'DarkModeFilled',
  'DictOutlined',
  'ExternalLinkOutlined',
  'HashLock',
  'IpfsOutlined',
  'KongLogo',
  'LightModeFilled',
  'MagnetOutlined',
  'ManTiedOutlined',
  'QrcodePrintOutlined',
  'QrcodeReadOutlined',
  'RtcOutlined',
  'TorrentFileFilled',
  'UTorrentFilled',
  'WebTorrentFilled',
  'WikipediaOutlined',
  'WomenWithMicroPhoneFilled',
];
// generated:end@types
